language: bash
services: docker

branches:
  only:
  - master

env:
  - VERSION=7.2 VARIANT= EXTRA_TAG=latest CLI_TAG=7.2-cli
  - VERSION=7.2 VARIANT=alpine EXTRA_TAG=alpine
  - VERSION=7.2 VARIANT=apache EXTRA_TAG=apache
  - VERSION=7.2 VARIANT=fpm EXTRA_TAG=fpm
  - VERSION=7.2 VARIANT=fpm-alpine EXTRA_TAG=fpm-alpine
  - VERSION=7.1 VARIANT= CLI_TAG=7.1-cli
  - VERSION=7.1 VARIANT=alpine EXTRA_TAG=alpine
  - VERSION=7.1 VARIANT=apache EXTRA_TAG=apache
  - VERSION=7.1 VARIANT=fpm EXTRA_TAG=fpm
  - VERSION=7.1 VARIANT=fpm-alpine EXTRA_TAG=fpm-alpine
  - VERSION=7.0 VARIANT= CLI_TAG=7.0-cli
  - VERSION=7.0 VARIANT=alpine
  - VERSION=7.0 VARIANT=apache
  - VERSION=7.0 VARIANT=fpm
  - VERSION=7.0 VARIANT=fpm-alpine EXTRA_TAG=fpm-alpine
  - VERSION=5.6 VARIANT= CLI_TAG=5.6-cli
  - VERSION=5.6 VARIANT=alpine
  - VERSION=5.6 VARIANT=apache
  - VERSION=5.6 VARIANT=fpm
  - VERSION=5.5 VARIANT= CLI_TAG=5.5-cli
  - VERSION=5.5 VARIANT=alpine
  - VERSION=5.5 VARIANT=apache
  - VERSION=5.5 VARIANT=fpm

before_script:
  - IMAGE="mileschou/phalcon"
  - IMAGE_VERSION="${VERSION}${VARIANT:+-$VARIANT}"
  - IMAGE_VERSION="${IMAGE_VERSION//'/'/-}"
  - IMAGE_NAME="$IMAGE:$IMAGE_VERSION"
  - echo "$IMAGE_NAME"

script:
  - docker build -t "$IMAGE_NAME" -f $VERSION/${VARIANT:-.}/Dockerfile .
  - if [ "" != "$EXTRA_TAG" ]; then docker tag "$IMAGE_NAME" "$IMAGE:$EXTRA_TAG" ; fi
  - if [ "" != "$CLI_TAG" ]; then docker tag "$IMAGE_NAME" "$IMAGE:$CLI_TAG" ; fi
  - docker images
  - docker run -i -t --rm $IMAGE_NAME php -m

after_success:
  - if [ "false" == "$TRAVIS_PULL_REQUEST" ]; then docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD ; fi
  - if [ "false" == "$TRAVIS_PULL_REQUEST" ]; then docker push $IMAGE ; fi
